version: "3.8"

services:
  todoapi:
    build: .
    container_name: todoapi
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=todoapi_db
      - DB_SCHEMA=public
      - DB_USER=todoapi_user
      - DB_PASSWORD=todoapi_password
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: todoapi-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=todoapi_db
      - POSTGRES_USER=todoapi_user
      - POSTGRES_PASSWORD=todoapi_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todoapi_user -d todoapi_db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  pgdata:
